# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Seonkyoo Yoon
email: yoonx213@umn.edu
description: > # this means to ignore newlines until "url:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
# footer_text: >
#   Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
#   Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
#   Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: May 20, 2020 # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: # your GitHub user name
twitter_username: # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: 7vsoWfwAAAAJ # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: Seonkyoo_Yoon # your profile on ResearchGate
blogger_url: # your blogger URL

contact_note: >
  You can even add a little note about which of these is the best way to reach you.

google_analytics: UA-XXXXXXXXX # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Thoughts
blog_description: a simple whitespace theme for academics

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: seonkyoo # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 1

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Yoon

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"

cvstyle:  kjhealy # [davewhipp | kjhealy]



# -----------------------------------------------------------------------------
# Resume settings
# -----------------------------------------------------------------------------
sass:
  sass_dir: _sass
  style: compressed

resume_avatar:                  "false"
resume_name:                    "Seonkyoo Yoon"
resume_title:                   "Ph.D. Hydrology"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yoonx213@umn.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"


resume_header_contact_info:     "<p> Department of Earth and Environmental Sciences, University of Minnesota, Twin Cites <br>116 Church Street SE, Ste 372, Minneapolis, MN 55455<br> email: <a href=mailto:yoonx213@umn.edu>yoonx213@umn.edu</a> | homepage: <a href=/>https://seonkyoo.github.io</a> </p>"
display_header_contact_info:    "true"

# resume_header_intro: "<p> Department of Earth and Environmental Sciences <br> University of Minnesota, Twin Cites <br>116 Church Street SE, Tate Hall 372<br>Minneapolis, MN 55455<br> email: <a href=mailto:yoonx213@umn.edu>yoonx213@umn.edu</a> <br> homepage: <a href=/>https://seonkyoo.github.io</a> </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_grants:          true
resume_section_fellowships:     true
resume_section_honors:          true
resume_section_publications:    true
resume_section_teaching:        true
resume_section_service:         true
# resume_section_mentoring:       true
# resume_section_service:         true
# resume_section_presentations:   true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/seonkyoo"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "/"
  # resume_medium_url:            "https://medium.com/@jglovier"
# resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
