# Fellowships
- service: Ad Hoc Reviewer
  organization1: Water Resources Research
  year1: 2020, 2021
  organization2: International Journal of Greenhouse Gas Control
  year2: 2017
  organization3: Stochastic Environmental Research and Risk Assessment
  year3: 2010
  # summary: $60,000

- service: Training Seminar Speaker
  organization1: Fourth Midwest OpenFOAM User Group Meeting
  year1: 2019
  summary: Delivered a lecture with interactive components designed for training engineers and researchers on how to use Lagrangian solvers in OpenFOAM for particulate flows

