# Fellowships
- service: Ad Hoc Reviewer
  organization1: International Journal of Greenhouse Gas Control
  year1: 2017
  organization2: Stochastic Environmental Research and Risk Assessment
  year2: 2010
  # summary: $60,000

- service: Training Seminar Speaker
  organization1: Fourth Midwest OpenFOAM User Group Meeting
  year1: 2019
  summary: Delivered 30-minute lecture with interactive components designed for training how to use Lagrangian solvers in OpenFOAM for particulate flow 

